---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tej-rolebinding
  namespace: dev
subject:
  - kind: User
    name: tej
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: tej-role
  apiGroup: rbac.authorization.k8s.io/v1
